name: Release BAD6 to Foundry

on:
  release:
    types: [published]   # fires when you publish a GitHub Release
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # needed to upload the zip to the release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # (Optional) validate/pack your system before zipping, if you have scripts

      - name: Build ZIP (system only files)
        run: |
          set -e
          rm -f bad6.zip
          zip -r bad6.zip \
            system.json \
            system/ \
            module/ \
            lang/ \
            templates/ \
            packs/ \
            assets/ \
            styles/ \
            dist/ \
            LICENSE README.md \
            -x "*.git*" "node_modules/*" ".github/*"

      - name: Attach ZIP to the GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bad6.zip

      # Publish to Foundry via the Package Release API
      # (uses cs96and/FoundryVTT-release-package which wraps the official API)
      - name: Publish to FoundryVTT
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          package-token: ${{ secrets.FOUNDRY_PACKAGE_TOKEN }}
          # Point to the manifest *for this specific release tag*
          manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/system.json
          # Optional: override Foundry-facing version/notes; if omitted, it reads from system.json
          # version: ${{ github.event.release.tag_name }}
          notes-url: https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}
